### PR TITLE
czech wordlist

### PR DESCRIPTION
**Pull request by lukascalda**
Hi, 
I would like to contribute with czech wordlist.

### CODE REVIEW

**Comment by lukascalda** [comment]
Job done, czech t9 keyboard is working already on my phone.

**Comment by sspanak** [comment]
Thanks for your contribution!

I can see you have uploaded two word lists, a smaller one and a larger one and you are making use of the smaller one. What is the reason for this? Looking at the smaller one, it contains 96k words, which is very little for functional everyday usage. Should they be merged?

**Comment by lukascalda** [comment]
Hi, no merging. The .csv one, the one yml refers to, is the right one. I had difficulties with the worldlist and I was trying different approaches. Those 96k words are ok, I am using the keyboard as is everyday since I made my build. It works amazingly good. Some words sometimes need to be added to dictionary, still it is perfectly functional as is by now.
I did not look yet if it possible to get user wordlist from the TT9 app. If it is, I will merge that one later with this already functional csv.
Cheers

**Comment by sspanak** [comment]
> Hi, no merging. The .csv one, the one yml refers to, is the right one. I had difficulties with the worldlist and I was trying different approaches. Those 96k words are ok, I am using the keyboard as is everyday since I made my build. It works amazingly good. Some words sometimes need to be added to dictionary, still it is perfectly functional as is by now.

That's my point. It will work fine with the words in the dictionary, but you will need to add new ones all the time. That's what I thought it may be better using the larger list. 

> I did not look yet if it possible to get user wordlist from the TT9 app. If it is, I will merge that one later with this already functional csv.

I am fine with merging it as it is and upgrading later. Unfortunately, exporting within the app is not possible at the moment. Filtering only the custom words will take significant amount of time and processing power, so I decided not to implement it. This may change after #366, which will hopefully boost the database performance.

However there may be a way. I suppose you are now using a debug variant of TT9, since you have packaged Czech yourself. Provided that you are also using Android Studio, you could start the app while your phone is connected to your computer, then you could export the `words` table from the database using Android Studio. After that, you could just send me the entire table export, even it contains words from other languages. I'll filter the new Czech words manually. I have handy scripts for the job.

**Pull request closed without merging**
