### PR TITLE
Add Turkish dictionary

### PR DESCRIPTION
**Pull request by fazilaltinel**

### CODE REVIEW

**Comment by sspanak** [comment]
@fazilaltinel, thanks for your contribution. The hunspell dictionaries are not always a good source of words. Sometimes, there are invalid ones, containing letters from other languages, sometimes, or containing numbers; in other cases, there are incorrectly capitalized ones ("DEMİRALİ") and whatnot.

I cannot merge the pull request in the current state. Please, clean up the dictionary. I can do so too, but not for the next release.

**Comment by alicanpamay** [comment]
Hey dear @sspanak! Firstly Thank you for this kind awesome project. Yesterday I ordered a qin f22 pro. So I want to contribute your project for Turkish language support. What can/should I do for  this contribution?

**Review by alicanpamay — CHANGES_REQUESTED** [review]
---
locale: tr-TR
dictionaryFile: tr-utf8.csv
layout:
  - [SPECIAL] # 0
  - [PUNCTUATION] # 1
  - [a, b, c, ç] # 2
  - [d, e, f] # 3
  - [g, h, ı, i, ğ] # 4
  - [j, k, l] # 5
  - [m, n, o, ö] # 6
  - [p, q, r, s, ş] # 7
  - [t, u, v, ü] # 8
  - [w, x, y, z] # 9


I thing this is better for Turkish layout.

**Comment by alicanpamay** [comment]
I cleared .csv file. It's done. I thing it's ready to go :)

[Uploading tr-utf8.csv…]()

**Comment by sspanak** [comment]
@alicanpamay, it would be better if you could find a word list from a respected university or an academy that regulates the language. For example, if you have "a big dicitionary of Turkish", that would guarantee good suggestions when typing. Since I don't speak the language, it is very difficult to me to search for such a dictionary in Turkish websites.

The list posted originally here is generated from subtitles. Such lists often have spelling mistakes and contain foreign or nonsense words. It can be used as the main source, but I would go for it if there are no other options.

Anyway, please go ahead and post the cleaned `.csv`. Even if you find a better source, I could add some of the words from this one and created an ever more complete dictionary.

> I don't know how I can upload the new csv file.

Click this button to attach it to your comment:
image

**Comment by sspanak** [comment]
>  Yeah i know those kind lists but i checked it. I saw it includes almost every inflected forms of verbs and so many useful words we use in daily conversations.

Perfect! It's all I wanted to hear, especially from a native speaker. Thanks for helping!

> Is there anything i can do for you? I'm ready to do everthing to see Turkish language support in next version :)

I think we are good now. I'll just merge the two lists and do small optimization for better searching speed.

**Comment by alicanpamay** [comment]
> I think we are good now. I'll just merge the two lists and do small optimization for better searching speed.

Many thanks for your efforts. If you need help, please let me know. I'm ready to help :)

**Comment by sspanak** [comment]
@alicanpamay, one more thing. I've received an email that you have requested some changes in the .yml file, but strangely, I can't see them on Github. Have you deleted your comment or has Github just failed? If have a change request, please try describing it in a new comment.

**Comment by sspanak** [comment]
Got it. Let's keep them in such case.

**Comment by sspanak** [comment]
@alicanpamay, I think I am done with the language. I've tried typing a couple of random Wikipedia articles and my impressions are:

1. The word amount could have been a bit higher. I've found that 1-2 words were missing. It is not perfect, but it is not terrible either. You will have to add new words sometimes, but it will be manageable. If you would like to contribute again at a later stage, you could export the added words and I would be happy to include them in a next version of TT9.
2. There are still a lot of words with the wrong text case. I've tried to fix as many as I could, but surely I have missed some. Again you are welcome to open a PR to correct them in the future.

With the above consideration, I will merge this PR and include Turkish in the next release. Thanks for helping and enjoy using TT9!

**Review by sspanak — APPROVED** [review]

**Comment by alicanpamay** [comment]
@sspanak many thanks for your efforts. If it's possible I can install app with Turkish option and try on daily conversation till the next version. Add new words while using it. Can we list the words as a separate one those I added? So we will get a better and more native word list :) How can i install app which include Turkish language to my smart phone?

**Comment by sspanak** [comment]
>  If it's possible I can install app with Turkish option and try on daily conversation till the next version. Add new words while using it. Can we list the words as a separate one those I added? So we will get a better and more native word list :)

You can export only the words you have added from Settings -> Languages -> Export. You can do so at any time, you don't have to rush it for the release. Actually, I would recommend using TT9 for at least a month, to get a better idea of the typing experience.

> How can i install app which include Turkish language to my smart phone?

You can't, unless you build your own APK. Or, if you consider making a small donation, I will build an early preview version.

**Comment by alicanpamay** [comment]
> You can export only the words you have added from Settings -> Languages -> Export. You can do so at any time, you don't have to rush it for the release. Actually, I would recommend using TT9 for at least a month, to get a better idea of the typing experience.
>
I'm a nokia generation boy. So I'm sure I won't have any problem about using. :) 

 
> You can't, unless you build your own APK. Or, if you consider making a small donation, I will build an early preview version.
>
Oh, understood. I thing I can build an apk. I'm just not very familiar with using github. Should I build with using files in this issue?

But I can make a donation for your awesome efforts anyway. 👍

**Comment by sspanak** [comment]
I am not sure what do you mean by "issue". If you want to try doing it yourself use the branch from this PR and follow the [dev guide](https://github.com/sspanak/tt9/blob/master/CONTRIBUTING.md). Just have in mind you will NOT be able to upgrade from your version to the official one. You will have to uninstall yours first, which will lead to losing all added words and settings. Make sure to export them before uninstalling.

**Comment by alicanpamay** [comment]
@sspanak I meant branch by 'issue'.  OK I'll try to make it. 

By the way not worthy to your efforts but I could buy a beer for now. Economic isn't going well in Turkey nowadays.

**Comment by alicanpamay** [comment]
Thank you! 
My first thoughts are awesome! It`s working very good. I will use and add necessary words those we use in daily conversations. See u  soon🙂

**Comment by alicanpamay** [comment]
@sspanak ok the last time im writing this subject for new words list.
[tt9-added-words-export--1716328627229.csv](https://github.com/sspanak/tt9/files/15395926/tt9-added-words-export--1716328627229.csv)
[tt9-added-words-export--1716328453326_125548.txt](https://github.com/sspanak/tt9/files/15395927/tt9-added-words-export--1716328453326_125548.txt)

Thanks...

**Comment by sspanak** [comment]
Thanks!

Here is my last comment here too, a summary of the update:
2-3 words seemed to be incorrectly capitalized, so I fixed that. Also, `iyi` was added to English, but I suppose it was by mistake, so I added it to Turkish.

Finally, 100 words is what I mean by "good amount of words". I was just not expecting that you have added so many in such a short period of time.

**Pull request merged**
