### PR TITLE
Add Finnish language

### PR DESCRIPTION
**Pull request by flaviozavan**
Adds support for typing in Finnish

### CODE REVIEW

**Comment by flaviozavan** [comment]
I forgot to create the dictionary readme in `docs`. Will populate that soon and update the PR

**Comment by flaviozavan** [comment]
Should be ready for review/merge

**Review by sspanak — CHANGES_REQUESTED** [review]
> Replaces the Finnish dictionary with a smaller one...

You replaced it with an empty file. Indeed, it is smaller! :smile: 

Please, include the actual word list and I will merge it.

**Comment by flaviozavan** [comment]
> You replaced it with an empty file. Indeed, it is smaller!

Ha! Not sure how that happened. That's all fixed now.

By the way, I noticed the font in the icon I created looks slimmer than the others. Though I followed the instructions exactly as described in the contribution guidelines. Is there a chance those are out-of-date?

**Review by sspanak — APPROVED** [review]

**Pull request merged**
