### PR TITLE
Add Thai language support

### LINKED ISSUE #628: Thai language support
I just finished adding a Thai language pattern on keypad and 5,000 words of Thai language. However when typing in Thai we don't usually need an automatically added space (since our language don't need that) I'm not sure if you can find a way to change that behavior specifically for Thai?

### PR DESCRIPTION
**Pull request by mmmmmob**
Resolves #628 

Adding Thai.yml and th-utf8.csv dictionary

### CODE REVIEW

**Comment by sspanak** [comment]
Please, see my comments in #628

**Comment by mmmmmob** [comment]
finished adding new dictionary with 18k words (tested and passed) @sspanak

**Comment by sspanak** [comment]
Excellent! Could you please also add links to the websites where you got the word lists from?

**Comment by mmmmmob** [comment]
Word lists based from [this repository](https://github.com/nv23/thai-wordlist) which you mentioned in the issue. I think this one is okay because the owner extracted all the words from the [Royal Institute Dictionary](https://dictionary.orst.go.th/)

There are some duplicate words in the original .txt file which I've cleared all of them and tested on Android Studio already.

**Comment by sspanak** [comment]
Perfect, thank you! I'll try to do my part as soon as possible, then merge it.

**Comment by sspanak** [comment]
Remaining tasks to do:
- Sort the dictionary
- Make sure the double vowels work properly.

**Review by sspanak — APPROVED** [review]

**Pull request merged**
